import React, { useState, useEffect } from 'react';
import { 
  Database, 
  Download, 
  Copy, 
  Check, 
  FileCode, 
  Sparkles, 
  RefreshCw, 
  CheckCircle2, 
  AlertCircle,
  ExternalLink,
  UploadCloud,
  Globe,
  Key
} from 'lucide-react';
import { 
  getSupabaseConfig, 
  saveCustomSupabaseConfig, 
  testSupabaseConnection, 
  pushAllLocalDataToSupabase 
} from '../lib/supabase.ts';
import { vacationStore } from '../lib/storage.ts';

const SUPABASE_SQL = `-- ============================================================================
-- SCRIPT SQL EXCLUSIVO PARA O SUPABASE (PostgreSQL)
-- Criação de Tabelas, Índices, Políticas RLS e Carga Completa de Dados
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Departamentos
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    max_concurrent_vacations INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Funcionários
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    cpf TEXT NOT NULL UNIQUE,
    registration_number TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'FUNCIONARIO',
    department_id BIGINT NOT NULL REFERENCES public.departments(id) ON DELETE RESTRICT,
    manager_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    hire_date DATE NOT NULL,
    job_title TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_employees_department_id ON public.employees(department_id);
CREATE INDEX IF NOT EXISTS idx_employees_manager_id ON public.employees(manager_id);

-- 3. Períodos Aquisitivos e Concessivos (CLT)
CREATE TABLE IF NOT EXISTS public.accrual_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    period_number INT NOT NULL,
    acquisitive_start DATE NOT NULL,
    acquisitive_end DATE NOT NULL,
    concessive_start DATE NOT NULL,
    concessive_end DATE NOT NULL,
    total_days_entitled INT DEFAULT 30 NOT NULL,
    days_taken INT DEFAULT 0 NOT NULL,
    days_sold INT DEFAULT 0 NOT NULL,
    days_remaining INT DEFAULT 30 NOT NULL,
    status TEXT DEFAULT 'EM_ANDAMENTO' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_concessive_order CHECK (concessive_start > acquisitive_start)
);

CREATE INDEX IF NOT EXISTS idx_accrual_periods_employee_id ON public.accrual_periods(employee_id);
CREATE INDEX IF NOT EXISTS idx_accrual_periods_concessive_end ON public.accrual_periods(concessive_end);

-- 4. Solicitações de Férias
CREATE TABLE IF NOT EXISTS public.vacation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    accrual_period_id BIGINT NOT NULL REFERENCES public.accrual_periods(id) ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_days INT NOT NULL,
    installment_number INT DEFAULT 1 NOT NULL,
    sell_days INT DEFAULT 0 NOT NULL,
    status TEXT DEFAULT 'PENDENTE' NOT NULL,
    has_department_overlap BOOLEAN DEFAULT FALSE NOT NULL,
    overlap_days INT DEFAULT 0 NOT NULL,
    conflicting_employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    notes TEXT,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_dates_order CHECK (end_date >= start_date),
    CONSTRAINT chk_fraction_min CHECK (duration_days >= 5),
    CONSTRAINT chk_installment_limit CHECK (installment_number BETWEEN 1 AND 3),
    CONSTRAINT chk_abono_limit CHECK (sell_days BETWEEN 0 AND 10)
);

CREATE INDEX IF NOT EXISTS idx_vacation_requests_employee_id ON public.vacation_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_dates ON public.vacation_requests(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_status ON public.vacation_requests(status);

-- 5. Habilitar Row Level Security (RLS)
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accrual_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vacation_requests ENABLE ROW LEVEL SECURITY;

-- 6. Políticas RLS seguras
DO $$ 
BEGIN
    BEGIN
        CREATE POLICY "departments_policy" ON public.departments 
            FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;

    BEGIN
        CREATE POLICY "employees_policy" ON public.employees 
            FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;

    BEGIN
        CREATE POLICY "accrual_periods_policy" ON public.accrual_periods 
            FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;

    BEGIN
        CREATE POLICY "vacation_requests_policy" ON public.vacation_requests 
            FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END $$;

-- 7. Carga de Departamentos
INSERT INTO public.departments (id, name, code, description) VALUES
(1, 'Tecnologia da Informação', 'TI', 'Engenharia de Software e Infraestrutura'),
(2, 'Recursos Humanos', 'RH', 'Departamento Pessoal e Treinamento'),
(3, 'Financeiro e Controladoria', 'FIN', 'Contabilidade e Compliance'),
(4, 'Operações e Logística', 'OPS', 'Supply Chain e Armazenagem'),
(5, 'Comercial e Vendas', 'COM', 'Expansão de Negócios')
ON CONFLICT (id) DO NOTHING;

-- 8. Carga de Colaboradores
INSERT INTO public.employees (id, name, email, cpf, registration_number, role, department_id, manager_id, hire_date, job_title) VALUES
(1, 'Carlos Eduardo Silveira', 'carlos.silveira@empresa.com.br', '111.222.333-44', 'MAT-1001', 'ADMIN', 1, NULL, '2021-02-15', 'Diretor de TI'),
(2, 'Ana Paula Mendes', 'ana.mendes@empresa.com.br', '222.333.444-55', 'MAT-1002', 'RH', 2, 1, '2022-03-01', 'Coordenadora de RH'),
(3, 'Juliana Castro', 'juliana.castro@empresa.com.br', '333.444.555-66', 'MAT-1003', 'RH', 2, 2, '2023-05-10', 'Analista de DP'),
(4, 'Rodrigo Albuquerque', 'rodrigo.ti@empresa.com.br', '444.555.666-77', 'MAT-1004', 'GESTOR', 1, 1, '2021-06-01', 'Tech Lead TI'),
(5, 'Lucas Pereira Rocha', 'lucas.rocha@empresa.com.br', '555.666.777-88', 'MAT-1005', 'FUNCIONARIO', 1, 4, '2022-08-15', 'Desenvolvedor Frontend'),
(6, 'Mariana Vasconcelos', 'mariana.v@empresa.com.br', '666.777.888-99', 'MAT-1006', 'FUNCIONARIO', 1, 4, '2023-01-20', 'Desenvolvedora Backend'),
(7, 'Felipe Sampaio', 'felipe.sampaio@empresa.com.br', '777.888.999-00', 'MAT-1007', 'FUNCIONARIO', 1, 4, '2024-02-10', 'Engenheiro DevOps')
ON CONFLICT (id) DO NOTHING;

-- 9. Carga de Períodos Aquisitivos e Concessivos CLT
INSERT INTO public.accrual_periods (id, employee_id, period_number, acquisitive_start, acquisitive_end, concessive_start, concessive_end, total_days_entitled, days_taken, days_sold, days_remaining, status) VALUES
(1, 5, 1, '2022-08-15', '2023-08-14', '2023-08-15', '2024-08-14', 30, 30, 0, 0, 'CONCEDIDO'),
(2, 5, 2, '2023-08-15', '2024-08-14', '2024-08-15', '2025-08-14', 30, 15, 0, 15, 'ADQUIRIDO'),
(3, 5, 3, '2024-08-15', '2025-08-14', '2025-08-15', '2026-08-14', 30, 0, 0, 30, 'ADQUIRIDO'),
(4, 6, 1, '2023-01-20', '2024-01-19', '2024-01-20', '2025-01-19', 30, 30, 0, 0, 'CONCEDIDO'),
(5, 6, 2, '2024-01-20', '2025-01-19', '2025-01-20', '2026-01-19', 30, 0, 0, 30, 'ADQUIRIDO'),
(6, 7, 1, '2024-02-10', '2025-02-09', '2025-02-10', '2026-02-09', 30, 0, 0, 30, 'ADQUIRIDO'),
(7, 3, 1, '2023-05-10', '2024-05-09', '2024-05-10', '2025-05-09', 30, 30, 0, 0, 'CONCEDIDO'),
(8, 3, 2, '2024-05-10', '2025-05-09', '2025-05-10', '2026-05-09', 30, 10, 0, 20, 'ADQUIRIDO')
ON CONFLICT (id) DO NOTHING;

-- 10. Carga de Solicitações de Férias
INSERT INTO public.vacation_requests (id, employee_id, accrual_period_id, start_date, end_date, duration_days, installment_number, sell_days, status, has_department_overlap, overlap_days, conflicting_employee_id, notes) VALUES
(1, 5, 2, '2026-11-03', '2026-11-17', 15, 1, 0, 'APROVADA_RH', FALSE, 0, NULL, '1ª fração de 15 dias (cumpre período >= 14 dias)'),
(2, 6, 2, '2026-11-12', '2026-11-26', 15, 1, 0, 'APROVADA_RH', TRUE, 6, 5, 'Sobreposição autorizada de 6 dias (12 a 17/11) com Lucas Rocha. Dentro da tolerância de até 7 dias.'),
(3, 3, 8, '2026-10-13', '2026-10-22', 10, 2, 0, 'APROVADA_RH', FALSE, 0, NULL, 'Férias de 10 dias após o feriado')
ON CONFLICT (id) DO NOTHING;

-- 11. Ajustar contadores de auto-incremento
SELECT setval('public.departments_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.departments));
SELECT setval('public.employees_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.employees));
SELECT setval('public.accrual_periods_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.accrual_periods));
SELECT setval('public.vacation_requests_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.vacation_requests));
`;

export const SqlViewerModal: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'supabase' | 'complete'>('supabase');
  const [copied, setCopied] = useState(false);

  // Estados de Conexão Supabase
  const [urlInput, setUrlInput] = useState('');
  const [keyInput, setKeyInput] = useState('');
  const [syncStatus, setSyncStatus] = useState<{ success: boolean; message: string } | null>(null);
  const [isExporting, setIsExporting] = useState(false);

  useEffect(() => {
    const cfg = getSupabaseConfig();
    setUrlInput(cfg.url || '');
    setKeyInput(cfg.anonKey || '');
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(SUPABASE_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = activeTab === 'supabase' ? 'supabase.sql' : 'database_completo.sql';
    const blob = new Blob([SUPABASE_SQL], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportDataNow = async () => {
    if (!urlInput.trim() || !keyInput.trim()) {
      setSyncStatus({ success: false, message: 'Por favor, informe a URL e a Anon Key do seu projeto Supabase abaixo.' });
      return;
    }

    saveCustomSupabaseConfig(urlInput.trim(), keyInput.trim());
    setIsExporting(true);
    setSyncStatus(null);

    // Testa a conexão
    const testRes = await testSupabaseConnection();
    if (!testRes.success) {
      setIsExporting(false);
      setSyncStatus(testRes);
      return;
    }

    // Exporta todos os dados para o Supabase
    const res = await pushAllLocalDataToSupabase({
      departments: vacationStore.getDepartments(),
      employees: vacationStore.getEmployees(),
      accrualPeriods: vacationStore.getAccrualPeriods(),
      vacations: vacationStore.getVacationRequests(),
    });

    setIsExporting(false);
    setSyncStatus(res);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-200 flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 text-indigo-600 text-xs font-bold uppercase tracking-wider mb-1">
            <Database className="w-4 h-4" />
            <span>Scripts SQL & Sincronização Supabase</span>
          </div>
          <h2 className="text-xl font-bold text-slate-900">
            Banco de Dados Relacional PostgreSQL
          </h2>
          <p className="text-xs text-slate-500">
            Script com DDL completo, políticas RLS para Supabase e carga de dados de teste.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold px-3.5 py-2 rounded-xl transition"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copiado!' : 'Copiar SQL Supabase'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="flex items-center space-x-1.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold px-4 py-2 rounded-xl transition shadow-md shadow-indigo-500/20"
          >
            <Download className="w-4 h-4" />
            <span>Baixar supabase.sql</span>
          </button>
        </div>
      </div>

      {/* Sincronização Rápida de Dados para o Supabase */}
      <div className="bg-gradient-to-r from-slate-900 to-indigo-950 text-white p-5 rounded-2xl border border-slate-800 shadow-md space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <span className="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center">
              <UploadCloud className="w-4 h-4 mr-1.5" />
              Sincronizar Dados da Aplicação com o Supabase
            </span>
            <p className="text-xs text-slate-300 mt-0.5">
              Seus dados locais não estão aparecendo no Supabase? Informe suas credenciais e envie todos os registros em 1 clique:
            </p>
          </div>
          <a
            href="https://supabase.com/dashboard"
            target="_blank"
            rel="noreferrer"
            className="text-xs text-blue-400 hover:text-blue-300 flex items-center font-medium"
          >
            Abrir Supabase Dashboard <ExternalLink className="w-3.5 h-3.5 ml-1" />
          </a>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div>
            <label className="text-slate-300 font-semibold mb-1 block flex items-center">
              <Globe className="w-3.5 h-3.5 mr-1 text-slate-400" />
              Project URL do Supabase:
            </label>
            <input
              type="text"
              placeholder="https://seu-projeto.supabase.co"
              value={urlInput}
              onChange={(e) => setUrlInput(e.target.value)}
              className="w-full bg-slate-800/90 border border-slate-700 rounded-xl p-2.5 text-white font-mono placeholder:text-slate-500 focus:outline-none focus:ring-1 focus:ring-emerald-400"
            />
          </div>

          <div>
            <label className="text-slate-300 font-semibold mb-1 block flex items-center">
              <Key className="w-3.5 h-3.5 mr-1 text-slate-400" />
              Anon Public API Key:
            </label>
            <input
              type="password"
              placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
              value={keyInput}
              onChange={(e) => setKeyInput(e.target.value)}
              className="w-full bg-slate-800/90 border border-slate-700 rounded-xl p-2.5 text-white font-mono placeholder:text-slate-500 focus:outline-none focus:ring-1 focus:ring-emerald-400"
            />
          </div>
        </div>

        {syncStatus && (
          <div className={`p-3 rounded-xl border text-xs flex items-center space-x-2 ${
            syncStatus.success 
              ? 'bg-emerald-950/80 text-emerald-200 border-emerald-700' 
              : 'bg-rose-950/80 text-rose-200 border-rose-700'
          }`}>
            {syncStatus.success ? (
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
            ) : (
              <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
            )}
            <span>{syncStatus.message}</span>
          </div>
        )}

        <div className="flex justify-end pt-1">
          <button
            onClick={handleExportDataNow}
            disabled={isExporting}
            className="bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-xs px-4 py-2.5 rounded-xl transition shadow-md flex items-center space-x-2 cursor-pointer disabled:opacity-50"
          >
            {isExporting ? (
              <>
                <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                <span>Enviando dados para o Supabase...</span>
              </>
            ) : (
              <>
                <UploadCloud className="w-3.5 h-3.5" />
                <span>Enviar Todos os Dados da Aplicação para o Supabase</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Script SQL Display */}
      <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-200 space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-bold text-slate-800 flex items-center">
            <FileCode className="w-4 h-4 text-blue-600 mr-2" />
            Script SQL Completo para Supabase (`scripts/supabase.sql`)
          </h3>
          <span className="text-[11px] text-slate-400">
            Cole no <strong>SQL Editor</strong> do Supabase e clique em <strong>Run</strong>
          </span>
        </div>

        <div className="bg-slate-950 rounded-xl p-4 border border-slate-800 shadow-inner overflow-x-auto text-xs font-mono text-slate-200 max-h-[500px] leading-relaxed select-all">
          <pre>{SUPABASE_SQL}</pre>
        </div>
      </div>
    </div>
  );
};
