-- ============================================================================
-- SCRIPT SQL PARA SUPABASE (TABELAS + CARGA COMPLETA DE DADOS)
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Tabela de Departamentos
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    max_concurrent_vacations INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela de Funcionários
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    cpf TEXT NOT NULL UNIQUE,
    registration_number TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'FUNCIONARIO',
    department_id BIGINT NOT NULL REFERENCES public.departments(id) ON DELETE RESTRICT,
    manager_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    hire_date DATE NOT NULL,
    job_title TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_employees_department_id ON public.employees(department_id);
CREATE INDEX IF NOT EXISTS idx_employees_manager_id ON public.employees(manager_id);

-- 3. Tabela de Períodos Aquisitivos e Concessivos (CLT)
CREATE TABLE IF NOT EXISTS public.accrual_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    period_number INT NOT NULL,
    acquisitive_start DATE NOT NULL,
    acquisitive_end DATE NOT NULL,
    concessive_start DATE NOT NULL,
    concessive_end DATE NOT NULL,
    total_days_entitled INT DEFAULT 30 NOT NULL,
    days_taken INT DEFAULT 0 NOT NULL,
    days_sold INT DEFAULT 0 NOT NULL,
    days_remaining INT DEFAULT 30 NOT NULL,
    status TEXT DEFAULT 'EM_ANDAMENTO' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_concessive_order CHECK (concessive_start > acquisitive_start)
);

CREATE INDEX IF NOT EXISTS idx_accrual_periods_employee_id ON public.accrual_periods(employee_id);
CREATE INDEX IF NOT EXISTS idx_accrual_periods_concessive_end ON public.accrual_periods(concessive_end);

-- 4. Tabela de Solicitações de Férias
CREATE TABLE IF NOT EXISTS public.vacation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    accrual_period_id BIGINT NOT NULL REFERENCES public.accrual_periods(id) ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_days INT NOT NULL,
    installment_number INT DEFAULT 1 NOT NULL,
    sell_days INT DEFAULT 0 NOT NULL,
    status TEXT DEFAULT 'PENDENTE' NOT NULL,
    has_department_overlap BOOLEAN DEFAULT FALSE NOT NULL,
    overlap_days INT DEFAULT 0 NOT NULL,
    conflicting_employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    notes TEXT,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_dates_order CHECK (end_date >= start_date),
    CONSTRAINT chk_fraction_min CHECK (duration_days >= 5),
    CONSTRAINT chk_installment_limit CHECK (installment_number BETWEEN 1 AND 3),
    CONSTRAINT chk_abono_limit CHECK (sell_days BETWEEN 0 AND 10)
);

CREATE INDEX IF NOT EXISTS idx_vacation_requests_employee_id ON public.vacation_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_dates ON public.vacation_requests(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_status ON public.vacation_requests(status);

-- 5. Habilitar Row Level Security (RLS)
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accrual_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vacation_requests ENABLE ROW LEVEL SECURITY;

-- 6. Políticas RLS seguras e 100% idempotentes
DROP POLICY IF EXISTS "departments_policy" ON public.departments;
DROP POLICY IF EXISTS "departments_all" ON public.departments;
CREATE POLICY "departments_policy" ON public.departments 
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "employees_policy" ON public.employees;
DROP POLICY IF EXISTS "employees_all" ON public.employees;
CREATE POLICY "employees_policy" ON public.employees 
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "accrual_periods_policy" ON public.accrual_periods;
DROP POLICY IF EXISTS "accrual_periods_all" ON public.accrual_periods;
CREATE POLICY "accrual_periods_policy" ON public.accrual_periods 
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "vacation_requests_policy" ON public.vacation_requests;
DROP POLICY IF EXISTS "vacation_requests_all" ON public.vacation_requests;
CREATE POLICY "vacation_requests_policy" ON public.vacation_requests 
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 7. Carga de Departamentos
INSERT INTO public.departments (id, name, code, description) VALUES
(1, 'Tecnologia da Informação', 'TI', 'Engenharia de Software e Infraestrutura'),
(2, 'Recursos Humanos', 'RH', 'Departamento Pessoal e Treinamento'),
(3, 'Financeiro e Controladoria', 'FIN', 'Contabilidade e Compliance'),
(4, 'Operações e Logística', 'OPS', 'Supply Chain e Armazenagem'),
(5, 'Comercial e Vendas', 'COM', 'Expansão de Negócios')
ON CONFLICT (id) DO NOTHING;

-- 8. Carga de Colaboradores
INSERT INTO public.employees (id, name, email, cpf, registration_number, role, department_id, manager_id, hire_date, job_title) VALUES
(1, 'Carlos Eduardo Silveira', 'carlos.silveira@empresa.com.br', '111.222.333-44', 'MAT-1001', 'ADMIN', 1, NULL, '2021-02-15', 'Diretor de TI'),
(2, 'Ana Paula Mendes', 'ana.mendes@empresa.com.br', '222.333.444-55', 'MAT-1002', 'RH', 2, 1, '2022-03-01', 'Coordenadora de RH'),
(3, 'Juliana Castro', 'juliana.castro@empresa.com.br', '333.444.555-66', 'MAT-1003', 'RH', 2, 2, '2023-05-10', 'Analista de DP'),
(4, 'Rodrigo Albuquerque', 'rodrigo.ti@empresa.com.br', '444.555.666-77', 'MAT-1004', 'GESTOR', 1, 1, '2021-06-01', 'Tech Lead TI'),
(5, 'Lucas Pereira Rocha', 'lucas.rocha@empresa.com.br', '555.666.777-88', 'MAT-1005', 'FUNCIONARIO', 1, 4, '2022-08-15', 'Desenvolvedor Frontend'),
(6, 'Mariana Vasconcelos', 'mariana.v@empresa.com.br', '666.777.888-99', 'MAT-1006', 'FUNCIONARIO', 1, 4, '2023-01-20', 'Desenvolvedora Backend'),
(7, 'Felipe Sampaio', 'felipe.sampaio@empresa.com.br', '777.888.999-00', 'MAT-1007', 'FUNCIONARIO', 1, 4, '2024-02-10', 'Engenheiro DevOps')
ON CONFLICT (id) DO NOTHING;

-- 9. Carga de Períodos Aquisitivos e Concessivos CLT
INSERT INTO public.accrual_periods (id, employee_id, period_number, acquisitive_start, acquisitive_end, concessive_start, concessive_end, total_days_entitled, days_taken, days_sold, days_remaining, status) VALUES
(1, 5, 1, '2022-08-15', '2023-08-14', '2023-08-15', '2024-08-14', 30, 30, 0, 0, 'CONCEDIDO'),
(2, 5, 2, '2023-08-15', '2024-08-14', '2024-08-15', '2025-08-14', 30, 15, 0, 15, 'ADQUIRIDO'),
(3, 5, 3, '2024-08-15', '2025-08-14', '2025-08-15', '2026-08-14', 30, 0, 0, 30, 'ADQUIRIDO'),
(4, 6, 1, '2023-01-20', '2024-01-19', '2024-01-20', '2025-01-19', 30, 30, 0, 0, 'CONCEDIDO'),
(5, 6, 2, '2024-01-20', '2025-01-19', '2025-01-20', '2026-01-19', 30, 0, 0, 30, 'ADQUIRIDO'),
(6, 7, 1, '2024-02-10', '2025-02-09', '2025-02-10', '2026-02-09', 30, 0, 0, 30, 'ADQUIRIDO'),
(7, 3, 1, '2023-05-10', '2024-05-09', '2024-05-10', '2025-05-09', 30, 30, 0, 0, 'CONCEDIDO'),
(8, 3, 2, '2024-05-10', '2025-05-09', '2025-05-10', '2026-05-09', 30, 10, 0, 20, 'ADQUIRIDO')
ON CONFLICT (id) DO NOTHING;

-- 10. Carga de Solicitações de Férias (com o teste da regra de sobreposição <= 7 dias)
INSERT INTO public.vacation_requests (id, employee_id, accrual_period_id, start_date, end_date, duration_days, installment_number, sell_days, status, has_department_overlap, overlap_days, conflicting_employee_id, notes) VALUES
(1, 5, 2, '2026-11-03', '2026-11-17', 15, 1, 0, 'APROVADA_RH', FALSE, 0, NULL, '1ª fração de 15 dias (cumpre período >= 14 dias)'),
(2, 6, 2, '2026-11-12', '2026-11-26', 15, 1, 0, 'APROVADA_RH', TRUE, 6, 5, 'Sobreposição autorizada de 6 dias (12 a 17/11) com Lucas Rocha. Dentro da tolerância de até 7 dias.'),
(3, 3, 8, '2026-10-13', '2026-10-22', 10, 2, 0, 'APROVADA_RH', FALSE, 0, NULL, 'Férias de 10 dias após o feriado')
ON CONFLICT (id) DO NOTHING;

-- 11. Ajustar contadores de auto-incremento para novas inserções (seguro para SERIAL ou IDENTITY)
DO $$
BEGIN
    PERFORM setval(pg_get_serial_sequence('public.departments', 'id'), COALESCE(MAX(id), 1)) FROM public.departments;
    PERFORM setval(pg_get_serial_sequence('public.employees', 'id'), COALESCE(MAX(id), 1)) FROM public.employees;
    PERFORM setval(pg_get_serial_sequence('public.accrual_periods', 'id'), COALESCE(MAX(id), 1)) FROM public.accrual_periods;
    PERFORM setval(pg_get_serial_sequence('public.vacation_requests', 'id'), COALESCE(MAX(id), 1)) FROM public.vacation_requests;
EXCEPTION WHEN OTHERS THEN
    NULL; -- Ignora caso as sequences usem nomes manuais
END $$;
